name: MICCAI_COMPARE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.2
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.8.18
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.1.0
  - six=1.16.0
  - sqlite=3.45.1
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - absl-py==0.14.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - cachetools==4.2.4
      - captum==0.7.0
      - certifi==2021.10.8
      - chardet==3.0.4
      - charset-normalizer==2.0.7
      - click==8.1.7
      - coverage==7.4.1
      - cycler==0.10.0
      - dnspython==2.6.1
      - dtcwt==0.12.0
      - exceptiongroup==1.2.0
      - filelock==3.13.1
      - fire==0.5.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gensim==4.3.2
      - google-auth==2.28.0
      - google-auth-oauthlib==1.0.0
      - googletrans==3.0.0
      - grad-cam==1.5.0
      - grpcio==1.60.1
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2024.2.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - huggingface-hub==0.20.3
      - hyperframe==5.2.0
      - idna==2.10
      - imageio==2.34.0
      - importlib-resources==6.1.1
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.3.2
      - kornia==0.7.1
      - lazy-loader==0.3
      - lightning-bolts==0.6.0.post1
      - lightning-lite==1.8.0
      - lightning-utilities==0.3.0
      - markdown==3.3.4
      - markupsafe==2.1.5
      - matplotlib==3.4.3
      - medclip==0.0.3
      - monai==1.3.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.21.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.1.1
      - opencv-python==4.9.0.80
      - pandas==2.0.3
      - pillow==10.2.0
      - pluggy==1.4.0
      - prodigyopt==1.0
      - protobuf==4.25.3
      - py3nvml==0.2.7
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.7
      - pymongo==4.6.1
      - pyparsing==2.4.7
      - pyshearlab==0.0.1
      - pytest==8.0.1
      - pytest-cov==4.1.0
      - pytorch-lightning==1.8.0
      - pytorch-lightning-bolts==0.3.2.post1
      - pytorch-wavelets==1.3.0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - quantus==0.5.3
      - regex==2023.12.25
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - rfc3986==1.5.0
      - rsa==4.7.2
      - safetensors==0.4.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - smart-open==7.0.1
      - sniffio==1.3.1
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.0
      - termcolor==2.4.0
      - textaugment==2.0.0
      - textblob==0.18.0.post0
      - threadpoolctl==3.3.0
      - tifffile==2023.7.10
      - timm==0.9.16
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.2.0
      - torchmetrics==0.11.4
      - torchray==1.0.0.2
      - torchvision==0.17.0
      - torchxrayvision==1.2.1
      - tqdm==4.66.2
      - transformers==4.38.1
      - triton==2.2.0
      - ttach==0.0.3
      - tzdata==2024.1
      - urllib3==1.26.7
      - werkzeug==2.0.2
      - wget==3.2
      - wrapt==1.16.0
      - xmltodict==0.13.0
      - yarl==1.9.4
